[manager]
# Layout ratios: [parent, current, preview]
# Use [0, 1, 2] for 2-pane layout: hide parent, show current directory, large preview
ratio = [0, 1, 2]

# Show hidden files by default
show_hidden = false

# Sort configuration
sort_by = "modified"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true

[preview]
# Enable file preview
tab_size = 2
max_width = 600
max_height = 900

# Image preview settings
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
# Configure file associations and preview
edit = [
    { run = '$EDITOR "$@"', desc = "Edit", block = true },
]

[plugin]
# Plugin configurations for better preview
preloaders = [
    # { name = "*", cond = "!mime", run = "mime", sync = true },
]

prepend_previewers = [
    # { name = "*/", run = "folder" },
    # { name = "*", run = "file" },
]

[input]
# Cursor configurations
cursor_blink = true

[log]
# Disable logs for cleaner output
enabled = false